sources:
  include:
    - .
    - ../../../Armstrong/Sources
  exclude:
    - ../../../Armstrong/Sources/Armstrong/Values/Implementations
    - ../../../Armstrong/Sources/Armstrong/Views/Implementations
    - ../../../Armstrong/Sources/Armstrong/Steps/Implementations
    - ../../../Armstrong/Sources/Armstrong/Generated.swift
templates:
  - ../../Templates
  - ../../../Armstrong/Templates/Shared
output: Generated.swift